### PR TITLE
Update players.yaml

### PR DESCRIPTION
**Pull request by gokhantahil**
Those are important Turkish players and streamer.

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Hello, how do Dr.Kozmonot and RipVanWinkle meet the notability requirements? I was not able to determine.

**Comment by gokhantahil** [comment]
They are both on the top 200.

Dr.Kozmonot plays 1v1 in general, he was in top 200 when i sent the commit and he participated to the some tournaments (for example : https://liquipedia.net/ageofempires/Empirematics/Gold_Championship)

And RipVanWinkle is in top 200 as well in the team game ladder.

**Comment by happyleavesaoc** [comment]
Requirement is top 200 on the 1v1 ladder -- if they have ever been top 200 there, they can be added. If not, please remove and I'll add the rest. Thanks!

**Comment by gokhantahil** [comment]
Ok, I'll remove Rip than. Thanks!

**Pull request closed without merging**
