### PR TITLE
Make Orjan come from Norway

### PR DESCRIPTION
**Pull request by simonsan**
I think he was already set to being from Norway from aoe2net, so let's do it as well here?

Was a bit confused searching for Viper here:
https://aoe2recs.com/players/120

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
He lives in Germany does he not?

**Comment by simonsan** [comment]
> He lives in Germany does he not?

Yes, it's a long discussion I guess and I actually see it the same. But he would still play for Norway in Nation Cup for example and we still say, he is the best Norwegian player. Furthermore he is listed under Norway in aoe2.club leaderboard [1] and I think he wanted to be listed with a norwegian flag on aoe2.net. So yeah, to make it consistent I would probably put it to Norway here as well.

[1]: https://aoe2.club/leaderboard/country/Norway

**Comment by simonsan** [comment]
He is playing with MbL for Norway in the 2v2 Worldcup ... so I'm of the opinion that we should stick to the country/flag people identify themselves with or want to be identified with. Regarding Viper I'm pretty sure also from his actions with aoe2net he is fine with a Norwegian flag. He was surprised that on the Matchmaking-Overlay was the German flag and people told him that's because of aoe2net API where we pull the data from, hence it was changed there. If we would have pulled the data from here we would probably came earlier to let it change, so this is just a consistency issue, I believe.

**Comment by happyleavesaoc** [comment]
Changed.

**Pull request merged**
