### PR TITLE
Adding ObaTheGreatt to players.yaml

### PR DESCRIPTION
**Pull request by jeronymo**
ObaTheGreatt has a page on the Liquipedia

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Thanks!

**Comment by simonsan** [comment]
> Thanks!

@happyleavesaoc Unfortunately this was merged prematurely, there was a suggestion still open fixing a whitespace issue. Also I want to recommend not merging any PRs that have a broken CI, otherwise CI is senseless.

**Comment by happyleavesaoc** [comment]
@simonsan I fixed it myself immediately after merge rather than asking contributor to fix.

**Comment by simonsan** [comment]
> @simonsan I fixed it myself immediately after merge rather than asking contributor to fix.

Not showing up here on master, could it have something to do with your merges or didn't push? Because master was broken :/

**Comment by happyleavesaoc** [comment]
:s I thought I did, well, thanks for fixing it.

**Comment by simonsan** [comment]
non ce problema, was just confused a bit about the merges without the fixing. glad we talked about the misunderstanding. :)

**Pull request merged**
