### PR TITLE
Add Morg_11 to players.yaml

### PR DESCRIPTION
**Pull request by Morg11**

### CODE REVIEW

**Comment by simonsan** [comment]
@Morg11 Can you collect your Voobly accounts please and post them here so we add them? I fixed your PR. Any Twitch stream to add?

**Comment by Morg11** [comment]
> @Morg11 Can you collect your Voobly accounts please and post them here so we add them? I fixed your PR. Any Twitch stream to add?
I haven't started stream yet, but I plan to soon
https://www.voobly.com/profile/view/125033680 Also my smurf

**Comment by simonsan** [comment]
> I haven't started stream yet, but I plan to soon
> https://www.voobly.com/profile/view/125033680 Also my smurf

> > I also had **a lot of smurfs** on voobly, but this is my very first and main acc

Hmm ok, doesn't seem a lot there. If you have more it makes sense to put them in here as also old recs get analysed and could be shown under your name etc.

**Comment by Morg11** [comment]
> > I haven't started stream yet, but I plan to soon
> > https://www.voobly.com/profile/view/125033680 Also my smurf
> 
> > > I also had **a lot of smurfs** on voobly, but this is my very first and main acc
> 
> Hmm ok, doesn't seem a lot there. If you have more it makes sense to put them in here as also old recs get analysed and could be shown under your name etc. You basically want to have all your accounts in here to connect them.

https://www.voobly.com/profile/view/125196962 https://www.voobly.com/profile/view/125206801

**Comment by simonsan** [comment]
Thank you :)

**Pull request merged**
