### PR TITLE
Added a few mpzza players

### PR DESCRIPTION
**Pull request by AndyGybels**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Not certain of the notability here. I haven't heard of these players.

**Comment by simonsan** [comment]
> Not certain of the notability here. I haven't heard of these players.

Me neither, but I ask myself which criteria we have for overall notability. Long-term players? Achievements? Well-known community members?

**Comment by AndyGybels** [comment]
Exactly, there are no guidelines to which players are applicable or not. These are just players that I know personally and thus verified.

**Comment by simonsan** [comment]
I think it makes sense to discuss this in general in #70 instead of in this PR.

**Comment by happyleavesaoc** [comment]
Notability requirements instituted @ https://github.com/SiegeEngineers/aoc-reference-data/commit/39c6825f1d682055c7936007b7e5f12e1d7bff40. Closing this PR.

**Pull request closed without merging**
