### PR TITLE
Update players.yaml

### PR DESCRIPTION
**Pull request by gokhantahil**
This player is not Ertug. You can ask to Scotty. He is Scotty's friend. I talked with him and he will post on zone.

### CODE REVIEW

**Comment by simonsan** [comment]
> This player is not Ertug. You can ask to Scotty. He is Scotty's friend. I talked with him and he will post on zone.

Hey there,
thank you for supporting this community effort. Looking forward to read the post. Please link it here then.

Cheers!

**Comment by gokhantahil** [comment]
Thanks for your answer, I post his voobly accounts & twitch & youtube channel as the comment of wrong update/commit of @happyleavesaoc. I thought that he was ertug as well but we had a discord meeting, he explained himself very well. He had a gpu problem, he stopped playing the game. He was around 1700 elo on mai 2020 which is nearly equivalent to 2000 right now. Asap I got his post, I’ll link you. 

Thanks!

**Comment by simonsan** [comment]
👍🏽

**Comment by happyleavesaoc** [comment]
@gokhantahil Merging for now.

**Pull request merged**
