### PR TITLE
[WIP] Liquipedia Update rework

### PR DESCRIPTION
**Pull request by simonsan**
Started to reimplement `liquipedia.py` object-oriented, also in regards to easily implement future CI

__Notes:__
- [De-/Serializing from/to Classes from/to YAML](https://yaml.readthedocs.io/en/latest/dumpcls.html)

### CODE REVIEW

**Comment by simonsan** [comment]
Factored out the CI part to a new PR (#110)

**Comment by happyleavesaoc** [comment]
What is the status of this?

**Comment by simonsan** [comment]
> What is the status of this?

I'm planning to continue working on this in the beginning of January. Haven't found enough time to focus on this between some other stuff.

**Comment by simonsan** [comment]
Forgot to ask, do you know if there happens to be any updates to the Liquipedia API soon? Bacause that was also a bit of a reason why I put this on pause for me, because if the API changes and the data we get, maybe this will make it easier to query other stuff and our data structures could change with it, which might make it easier to compare and update or something. @happyleavesaoc

**Comment by happyleavesaoc** [comment]
I haven't seen any official date. I recommend we proceed with the SMW API so that we can get back to having automated updates.

**Comment by happyleavesaoc** [comment]
Anything new here? We have been missing automated updates for some time now and data is becoming quite stale.

**Comment by simonsan** [comment]
> Anything new here? We have been missing automated updates for some time now and data is becoming quite stale.

It's on the list and will do it next! Need to finish other stuff before though.

**Pull request closed without merging**
