### PR TITLE
added bobdedestructor, danish player

### PR DESCRIPTION
**Pull request by HeavenlyChorus**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Does he meet notability requirements?

**Comment by simonsan** [comment]
I don't think so.

**Comment by HeavenlyChorus** [comment]
> Does he meet notability requirements?

he represented denmark in nation cups 3 times

**Comment by happyleavesaoc** [comment]
> > Does he meet notability requirements?
> 
> he represented denmark in nation cups 3 times, and was a well known voobly player

The specific requirements are in the README file.

**Pull request closed without merging**
