### PR TITLE
Added 1ron_chef, streamer

### PR DESCRIPTION
**Pull request by Stalfur**

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
Sorry, I don't believe this person meets notability requirements.

**Comment by Stalfur** [comment]
Guess he's stuck with not working !match then

**Comment by happyleavesaoc** [comment]
Why? The dashboard command work for every streamer that registers on the website.

**Comment by Stalfur** [comment]
Apologies, wasn't clear to me

**Pull request closed without merging**
