### PR TITLE
Add another Ertug account

### PR DESCRIPTION
**Pull request by simonsan**
Source:
https://www.aoezone.net/threads/please-ban-ertug.172932/

Besıdes all these accounts, he also plays on hıs frıend’s accounts. He asks them to gıve theır accounts so he can play some games agaınst noobs. The accounts of hıs frıends where he plays on are:

    AlperenAOE: https://aoe2.net/#profile-874604
    Ibyy123: https://aoe2.net/#profile-2848144
    EROTİCBAKİREE: https://aoe2.net/#profile-2674888
    ErotıkBakıre: https://aoe2.net/#profile-4602573
    Darkmatter: https://aoe2.net/#profile-3218089
    FNUL: https://aoe2.net/#profile-3959793

What do we do with these ^^ ?

Do we want to create an `Ertug-Enablers` nick or just add them as well to Ertug?

### CODE REVIEW

**Comment by happyleavesaoc** [comment]
There is already precedent for tagging shared accounts with the highest-ranked user. I think that is reasonable to do in this case.

However, this is a sensitive matter and I do not want to brand these accounts with Ertug's name without a second, independent verification.

**Comment by DeePDeBRiS** [comment]
Hey I came here to confirm the account I know where a (aka ertug) should be placed. These are the accounts I'm 100% sure

AlperenAOE: https://aoe2.net/#profile-874604
Ibyy123: https://aoe2.net/#profile-2848144
EROTICBAKIREE: https://aoe2.net/#profile-2674888
ErotıkBakıre: https://aoe2.net/#profile-4602573
Darkmatter: https://aoe2.net/#profile-3218089

This was the account ertug played with the name F8.KASMA, with this account he played against Nili: https://aoe2.net/#profile-4863157

I also think it is good for everyone to put their names behind their names so that they know what to expect and not be too upset with their loss. But the account of FNUL I am not sure about. There was a rumour, but eventually he did not let him play as far as I am aware.

**Comment by DeePDeBRiS** [comment]
@simonsan @happyleavesaoc

**Comment by simonsan** [comment]
> There is already precedent for tagging shared accounts with the highest-ranked user. I think that is reasonable to do in this case.

Should I do this within this PR?

**Comment by happyleavesaoc** [comment]
Not comfortable moving forward here given the sensitivity. If real evidence surfaces (not hearsay) then we can add these other accounts. I originally asked for an independent validation but I think that still leaves us exposed to various conflicts of interest.

**Comment by ReeLDeePDeBRiS** [comment]
Hi guys,

They will be caught again as they were caught before!
https://www.aoezone.net/threads/false-accusations-about-me.174731/

Cowards who hide their real identities by opening fake accounts are now targeting me, opening my fake account.
I have the alias DeePDeBRiS, avoid fakes!
Sorry to have to prove myself, that we polluted github with such nonsense. 

https://steamcommunity.com/profiles/76561198053289808
https://www.twitch.tv/deepdebris
https://www.aoezone.net/members/deepdebris.103934/

**Comment by simonsan** [comment]
@ReeLDeePDeBRiS Sorry, I don't really understand what you mean. Do you need something?

**Comment by ReeLDeePDeBRiS** [comment]
> Hey I came here to confirm the account I know where a (aka ertug) should be placed. These are the accounts I'm 100% sure
> 
> AlperenAOE: https://aoe2.net/#profile-874604
> Ibyy123: https://aoe2.net/#profile-2848144
> EROTICBAKIREE: https://aoe2.net/#profile-2674888
> ErotıkBakıre: https://aoe2.net/#profile-4602573
> Darkmatter: https://aoe2.net/#profile-3218089
> 
> This was the account ertug played with the name F8.KASMA, with this account he played against Nili: https://aoe2.net/#profile-4863157
> 
> I also think it is good for everyone to put their names behind their names so that they know what to expect and not be too upset with their loss. But the account of FNUL I am not sure about. There was a rumour, but eventually he did not let him play as far as I am aware.
> 
> Hope this is enough information to update the aoe2.net account names, if not, feel free to ask around in the Turkish community by reaching out to me on Discord: DeePDeBRiS#2364.
This is the dialogue I should have written

> @ReeLDeePDeBRiS Sorry, I don't really understand what you mean. Do you need something?
I have to write a quick reply, hurriedly write in your dialogue, sorry

**Comment by ReeLDeePDeBRiS** [comment]
> Hey I came here to confirm the account I know where a (aka ertug) should be placed. These are the accounts I'm 100% sure
> 
> AlperenAOE: https://aoe2.net/#profile-874604
> Ibyy123: https://aoe2.net/#profile-2848144
> EROTICBAKIREE: https://aoe2.net/#profile-2674888
> ErotıkBakıre: https://aoe2.net/#profile-4602573
> Darkmatter: https://aoe2.net/#profile-3218089
> 
> This was the account ertug played with the name F8.KASMA, with this account he played against Nili: https://aoe2.net/#profile-4863157
> 
> I also think it is good for everyone to put their names behind their names so that they know what to expect and not be too upset with their loss. But the account of FNUL I am not sure about. There was a rumour, but eventually he did not let him play as far as I am aware.
> 
> Hope this is enough information to update the aoe2.net account names, if not, feel free to ask around in the Turkish community by reaching out to me on Discord: DeePDeBRiS#2364.

you are not real, imitating me, this is legally a crime!

**Comment by ReeLDeePDeBRiS** [comment]
> Hey I came here to confirm the account I know where a (aka ertug) should be placed. These are the accounts I'm 100% sure
> 
> AlperenAOE: https://aoe2.net/#profile-874604
> Ibyy123: https://aoe2.net/#profile-2848144
> EROTICBAKIREE: https://aoe2.net/#profile-2674888
> ErotıkBakıre: https://aoe2.net/#profile-4602573
> Darkmatter: https://aoe2.net/#profile-3218089
> 
> This was the account ertug played with the name F8.KASMA, with this account he played against Nili: https://aoe2.net/#profile-4863157
> 
> I also think it is good for everyone to put their names behind their names so that they know what to expect and not be too upset with their loss. But the account of FNUL I am not sure about. There was a rumour, but eventually he did not let him play as far as I am aware.
> 
> Hope this is enough information to update the aoe2.net account names, if not, feel free to ask around in the Turkish community by reaching out to me on Discord: DeePDeBRiS#2364.

Hi guys,

They will be caught again as they were caught before!
https://www.aoezone.net/threads/false-accusations-about-me.174731/

Cowards who hide their real identities by opening fake accounts are now targeting me, opening my fake account.
I have the alias DeePDeBRiS, avoid fakes!
Sorry to have to prove myself, that we polluted github with such nonsense.

https://steamcommunity.com/profiles/76561198053289808
https://www.twitch.tv/deepdebris
https://www.aoezone.net/members/deepdebris.103934/

**Comment by simonsan** [comment]
> 
> 
> > @ReeLDeePDeBRiS Sorry, I don't really understand what you mean. Do you need something?
> 
> I have to write a quick reply, hurriedly write in your dialogue, sorry

Sorry, I don't understand what you are talking about. I'll lock this topic for now.

**Pull request closed without merging**
