### PR TITLE
[Breaking Change] Renaming "platforms->de" to "platforms->rl" to support game indepent accounts using RelicLink ID

### PR DESCRIPTION
**Pull request by simonsan**

### CODE REVIEW

**Comment by simonsan** [comment]
Still missing changes to CI to support `rl`, please don't merge.

**Comment by happyleavesaoc** [comment]
How are we distinguishing `aoe2` players from `aoe4` players?

**Comment by simonsan** [comment]
> How are we distinguishing `aoe2` players from `aoe4` players?

I think that this is on the people that use an API to get the more information from a player on that specific platform e.g. using "age2" as a parameter to `game` on the public AoE API. For example it's also not done on Voobly, people could also play Age of Mythology or SWGB there and it isn't separated. I wouldn't introduce a new `key` for the game people play, as this would be too much maintenance effort (imho). I see this more as an effort to collect the IDs people have on a specific platform and the developers using this information use the ID to find the information they need.

**Comment by happyleavesaoc** [comment]
It is a matter of notability though. An aoe4 player may not be notable in aoe2, and there's no way for consumers to know which game is the relevant one if they play both. This assumes that aoe4 players might be added after this change. If that's *not* the case, then there's no reason to change the key name, of course.

**Comment by happyleavesaoc** [comment]
w.r.t. voobly -- same problem exists but it's effectively historical at this point and there's no interest that I know of to add voobly AoM or SWGB players.

**Comment by simonsan** [comment]
> It is a matter of notability though. An aoe4 player may not be notable in aoe2, and there's no way for consumers to know which game is the relevant one if they play both. This assumes that aoe4 players might be added after this change. If that's _not_ the case, then there's no reason to change the key name, of course.

Then I would change the third entry in the notability guidelines like so:

"Was ever a top 250 player on the primary competitive ladder for at least three months."

Which would make it game independent.

**Comment by happyleavesaoc** [comment]
Consumers of this data (myself included) may care about what a game a player is notable in. If we expand the scope to more than one game, we need to accommodate accordingly.

With that said, if the intention is to add aoe4 players here, we should also define inclusion criteria for them or adopt existing criteria, sure. That's independent of the concern.

**Comment by simonsan** [comment]
> Consumers of this data (myself included) may care about what a game a player is notable in. If we expand the scope to more than one game, we need to accommodate accordingly.

We can add a field `notability` to each player which is binary data encoding the notability from the left like so - with the advantage, that we can always add games/notabilities to the right.

**Notability table**

| aoe1 | aoe2 | aoe3 | aoe4 | (..future additions..) |
|:----:|:----:|:----:|:----:|:----------------------:|
|  0   |   1  |   0  |   1  |           (0)          |

So the notability for this player would be:

`0101` - which is notable in AoE2 and AoE4

**Comment by happyleavesaoc** [comment]
I think a `notability` field definitely solves our problem, good idea!. The maintenance burden is fairly low. We can also partially automate it based on Liquipedia categories.

I'm not in favor of an encoding. One of the benefits of YAML is the readability, which we would be compromising. I have seen non-technical users reference this file so there's definitely an incentive to keep it unobfuscated.

What about:

```yaml
notability:
  - aoe2
  - aoe3
```

**Comment by happyleavesaoc** [comment]
The "notability score" idea is pretty interesting but definitely introduces more work. I'd kind of be in favor of adding a script that computes a score and writes it to the file, then the heuristic algorithm could be smarter. But either way that's another project.

**Comment by simonsan** [comment]
> I think a `notability` field definitely solves our problem, good idea!. The maintenance burden is fairly low. We can also partially automate it based on Liquipedia categories.
> 
> I'm not in favor of an encoding. One of the benefits of YAML is the readability, which we would be compromising. I have seen non-technical users reference this file so there's definitely an incentive to keep it unobfuscated.
> 
> What about:
> 
> ```yaml
> notability:
>   - aoe2
>   - aoe3
> ```

I think that's better as I agree with the readability aspect. Though I'm not sure about the `Array of Strings`.

What would you think of:
```yaml
 notability:
     isAoE2: true,
     isAoE4: false,
```

That would make it easier in programming I think as we would just check for a `Boolean`.


> The "notability score" idea is pretty interesting but definitely introduces more work. I'd kind of be in favor of adding a script that computes a score and writes it to the file, then the heuristic algorithm could be smarter. But either way that's another project.

I can reference it in a new issue and extract some ideas from it for the future.

**Comment by happyleavesaoc** [comment]
```yaml
notability:
  - aoe2: true
  - aoe4: false
 ```
should be fine

**Comment by simonsan** [comment]
@happyleavesaoc Rebased

**Review by happyleavesaoc — APPROVED** [review]

**Pull request merged**
